version: "3.7"
services:
  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=pap

  app:
    build:
      context: .
      dockerfile: ./Docker/app.Dockerfile
    volumes:
      - ./var/app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db